### ISSUE TITLE
SZXX V3 : string with multiple successives spaces are modified

### ISSUE THREAD

**Issue by Chimrod** [asemio/SZXX#3]
The file in attachement contains the text `ABC  DEF` There are two spaces between the words.

When reading the file, the two spaces are flatten into a single one:

```
$ dune exe util/cli.exe -- show_json test.xlsx
[ "ABC DEF" ]
```
[test.xlsx](https://github.com/user-attachments/files/18200424/test.xlsx)

**Comment by Chimrod** [comment]
After some tests, it looks like excel only add [xml:space="preserve"](https://www.w3.org/TR/xml/#sec-white-space) attributes when there are spaces in the begining or the end of the text node. Multiple spaces inside the node seems always significant.

As a consequence, I’ve update the function render from xml.ml in this way:

```ocaml
  let render attrs text =
    match Queue.length text with
    | 0 -> ""
    | 1 when (Queue.get text 0).literal -> (Queue.get text 0).raw
    | _ ->
      let final = Buffer.create 16 in
      let preserve_space = lazy (preserve_space attrs) in
      let _prev_ws =
        Queue.fold text ~init:(false, false) ~f:(fun ((after_first, prev_ws) as acc) -> function
          | { raw = ""; _ } -> acc
          | {  raw ; literal } when literal || force preserve_space ->
            if after_first && not prev_ws then Buffer.add_char final ' ';
            Buffer.add_string final raw;
            true, is_ws raw.[String.length raw - 1]
          | { raw; _ } -> 
            Buffer.add_string final (String.strip ~drop:is_ws raw);
            (false, false)
        )
```

**Comment by SGrondin** [comment]
Thanks for the bug report! [It turns out to be a little bit more complicated than just calling `String.strip ~drop:is_ws`](https://github.com/asemio/SZXX/commit/e5c6193783a093b98d2f856e601a7aa1857b0442) but your updated `render` was a good starting place. 
I was also able to avoid allocating the stripped string entirely.

The fix will be released as version 3.1.0 shortly: https://github.com/ocaml/opam-repository/pull/27167

**Comment by Chimrod** [comment]
Thanks for your very quick correction! and maintaining this branch! I’s a pity I'm still not able to switch to the latest branch ([because of this issue](https://github.com/ocaml-multicore/eio/issues/125)) but I can still live with this…

**Comment by SGrondin** [comment]
I was lucky to see this issue right away!
About Eio, it's looking like Windows support is becoming a higher priority so you may get your wish in 2025, maybe? 🤞 
By the way, once you switch to Eio, look into [lwt_eio](https://github.com/ocaml-multicore/lwt_eio), it can "wrap" Lwt code inside of Eio code and vice versa. It allows you to progressively migrate a large codebase without having to break everything simultaneously.

**Comment by SGrondin** [comment]
Version `3.1.0` is now on OPAM
